// This file is auto-generated by @hey-api/openapi-ts

export type OrderData = {
    name: string;
    email: string;
    phoneNo: string;
    address: string;
    products: Array<{
        id?: number;
        quantity?: number;
    }>;
};

export type Product = {
    id?: number;
    name?: string;
    model?: string;
    description?: string;
    image?: string;
    price?: number;
    quantity?: number;
    category?: 'ROLEX' | 'OMEGA' | 'ZENITH';
};

export type ProductInput = {
    id?: number;
    name: string;
    image?: Blob | File;
    model: string;
    description: string;
    price: number;
    quantity: number;
    category?: 'ROLEX' | 'OMEGA' | 'ZENITH';
};

export type UserInput = {
    name: string;
    email: string;
    password: string;
    confirmPassword: string;
};

export type LoginInput = {
    email: string;
    password: string;
};

export type UserResponse = {
    name?: string;
    email?: string;
};

export type PostCartsData = {
    body: Array<{
        productId?: number;
        quantity?: number;
    }>;
    path?: never;
    query?: never;
    url: '/carts';
};

export type PostCartsErrors = {
    /**
     * Invalid product ID
     */
    400: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type PostCartsResponses = {
    /**
     * Carts item array
     */
    200: Array<{
        id?: number;
        name?: string;
        image?: string;
        model?: string;
        description?: string;
        price?: number;
        quantity?: number;
        category?: 'ROLEX' | 'OMEGA' | 'ZENITH';
    }>;
};

export type PostCartsResponse = PostCartsResponses[keyof PostCartsResponses];

export type GetOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/orders';
};

export type GetOrdersErrors = {
    /**
     * Orders not found
     */
    404: unknown;
};

export type GetOrdersResponses = {
    /**
     * A list of orders
     */
    200: unknown;
};

export type PostOrdersData = {
    body: OrderData;
    path?: never;
    query?: never;
    url: '/orders';
};

export type PostOrdersErrors = {
    /**
     * Invalid request
     */
    400: unknown;
};

export type PostOrdersResponses = {
    /**
     * Order created successfully
     */
    201: unknown;
};

export type PatchOrdersByIdData = {
    body: {
        orderStatus?: 'PENDING' | 'ACCEPTED' | 'REJECTED' | 'CANCELLED';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/{id}';
};

export type PatchOrdersByIdErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Order not found
     */
    404: unknown;
};

export type PatchOrdersByIdResponses = {
    /**
     * Order updated successfully
     */
    200: unknown;
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products';
};

export type GetProductsResponses = {
    /**
     * List of products
     */
    200: Array<Product>;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type PostProductsData = {
    body: ProductInput;
    path?: never;
    query?: never;
    url: '/products';
};

export type PostProductsErrors = {
    /**
     * Invalid input or file format
     */
    400: unknown;
};

export type PostProductsResponses = {
    /**
     * Product created successfully
     */
    201: unknown;
};

export type DeleteProductsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}';
};

export type DeleteProductsByIdErrors = {
    /**
     * Invalid product ID
     */
    400: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type DeleteProductsByIdResponses = {
    /**
     * Product deleted successfully
     */
    204: void;
};

export type DeleteProductsByIdResponse = DeleteProductsByIdResponses[keyof DeleteProductsByIdResponses];

export type GetProductsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}';
};

export type GetProductsByIdErrors = {
    /**
     * Invalid product ID
     */
    400: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type GetProductsByIdResponses = {
    /**
     * A single product
     */
    200: Product;
};

export type GetProductsByIdResponse = GetProductsByIdResponses[keyof GetProductsByIdResponses];

export type PatchProductsByIdData = {
    body: ProductInput;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}';
};

export type PatchProductsByIdErrors = {
    /**
     * Invalid product ID
     */
    400: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type PatchProductsByIdResponses = {
    /**
     * Product updated successfully
     */
    200: unknown;
};

export type PostRegisterData = {
    body: UserInput;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * User already exists or validation failed
     */
    400: unknown;
};

export type PostRegisterResponses = {
    /**
     * User registered successfully
     */
    201: unknown;
};

export type GetLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login';
};

export type GetLoginErrors = {
    /**
     * Unauthorized
     */
    401: {
        message?: string;
    };
};

export type GetLoginError = GetLoginErrors[keyof GetLoginErrors];

export type GetLoginResponses = {
    /**
     * Authenticated user info
     */
    200: {
        message?: string;
        user_data?: UserResponse;
    };
};

export type GetLoginResponse = GetLoginResponses[keyof GetLoginResponses];

export type PostLoginData = {
    body: LoginInput;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Invalid credentials
     */
    400: unknown;
};

export type PostLoginResponses = {
    /**
     * Login successful
     */
    200: {
        message?: string;
        user_data?: UserResponse;
    };
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    /**
     * Successfully logged out
     */
    200: unknown;
};

export type GetGetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/getStats';
};

export type GetGetStatsResponses = {
    /**
     * Product Stats
     */
    200: {
        productLeft?: number;
        soldProducts?: number;
        totalOrders?: number;
        totalProducts?: number;
    };
};

export type GetGetStatsResponse = GetGetStatsResponses[keyof GetGetStatsResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};